#!/usr/bin/env python3
from pathlib import Path
import traceback
here=Path(__file__).parent
base=here/'r36_cert_driver.py'
src=base.read_text()

# r37 intentionally retains the full green r36 certification chain but substitutes
# the deterministic r37 kernel transform and adapts only assertions invalidated by
# the physical r36 evidence (new endpoint row, Stop Endpoint recovery, PS/2 priority).

def one(old,new,label):
    global src
    n=src.count(old)
    if n!=1: raise SystemExit(f'r37 cert anchor {label} count {n}')
    src=src.replace(old,new,1)

def alln(old,new,count,label):
    global src
    n=src.count(old)
    if n!=count: raise SystemExit(f'r37 cert anchor {label} count {n}, expected {count}')
    src=src.replace(old,new)

# Use the r37 patch anywhere r36 would have reconstructed its kernel.
alln('patch_v108_r36_nonblocking_interrupt_recovery.py','patch_v108_r37_g750jm_xhci_ring_ps2.py',2,'patch path')
one("with tempfile.TemporaryDirectory(prefix='r36-ident-') as td:","with tempfile.TemporaryDirectory(prefix='r37-ident-') as td:",'identity temp')
alln('r36_sha','r37_sha',3,'identity variable')
alln("kernel-r36.nx","kernel-r37.nx",2,'kernel evidence name')

# r37 keeps the r36 helpers but extends the command path with Stop Endpoint.
one("req('fn v136_xhci_command_endpoint' in s and '(typ!=14 && typ!=16)' in s,'r36 bounded Reset/Set-TR-Dequeue command path missing')",
    "req('fn v136_xhci_command_endpoint' in s and '(typ!=14 && typ!=15 && typ!=16)' in s,'r37 bounded Reset/Stop/Set-TR-Dequeue command path missing')",'command model gate')
# New physical row replaces the r36 row in both the direct model gate and the
# private r35 compatibility gate generated by the inherited driver.
alln('v108_text_r36_v136','v108_text_r37_v137',2,'physical row symbol')
one("req('ps2_poll_fallback_burst_v112(input_state,24);' in s,'r36 PS/2 fallback service missing')",
    "req('ps2_poll_fallback_burst_v112(input_state,48);' in s,'r37 PS/2 priority fallback service missing')",'PS2 priority model gate')

# Add r37-specific structural requirements immediately after the retained HM87
# interval proof. These protect the exact physical repairs from accidental loss.
needle="    req('var v:u64=binterval; var p:u64=0; while v>1 { v=v/2; p=p+1; }' in s,'r36 lost r35b LS/FS interval repair')"
extra=needle+"""
    req(r37_sha=='03f446845e111e35b8cff6b216c5fee2d214dc0a4d6e25898f8a03b891c0c511','r37 exact kernel identity mismatch '+r37_sha)
    req('volatile_write32(tring+4088,0); volatile_write32(tring+4092,6147);' in s,'r37 HID Link TRB control placement repair missing')
    req('volatile_write64(tring+4088,6147)' not in s,'r37 stale malformed HID Link TRB remains')
    req('fn v137_xhci_hid_rebase_ring' in s and 'volatile_write64(xhci_state+408,0)' in s and 'volatile_write64(xhci_state+800,1)' in s,'r37 deterministic HID transfer-ring rebase missing')
    req('v136_xhci_command_endpoint(xhci_state,15,0)' in s,'r37 bounded Stop Endpoint recovery missing')
    req('let deq=volatile_read64(ep+8)' in s and 'volatile_write64(xhci_state+2824,qidx)' in s and 'volatile_write64(xhci_state+2832,dcs)' in s,'r37 hardware endpoint dequeue telemetry missing')
    req('if kicks<3' in s and 'volatile_read64(xhci_state+2816)<2' in s,'r37 bounded no-progress recovery policy missing')
    req('return ps2_elan4_motion_v112(input_state,a,b);' in s,'r37 Elantech v4 motion packets still dropped')
    req('if typ>=1 && typ<=3 {' in s,'r37 Elantech v4 button synchronization missing')
    req('ps2_poll_fallback_burst_v112(input_state,48);' in s,'r37 PS/2 priority burst missing')
    req('dnow-last_r37_draw>=1000000000' in s,'r37 diagnostic redraw throttle missing')
    req('last_r36_k' not in s,'r37 stale per-kick telemetry redraw state remains')
"""
one(needle,extra,'r37 model injection')

# Advance sealed image/evidence identity and physical history from r36 to r37.
one('Frames-0.9.98-v108-r36-Nonblocking-xHCI-Interrupt-Recovery-Rufus-UEFI.iso',
    'Frames-0.9.98-v108-r37-G750JM-xHCI-Ring-Elantech-Recovery-Rufus-UEFI.iso','ISO name')
one('R36-SHA.txt','R37-SHA.txt','SHA evidence name')
one('R25K-R36.patch','R25K-R37.patch','patch evidence name')
one('FRAMES_V108_R36','FRAMES_V108_R37','ISO label')
one("(ROOT/'evidence/R36-AGGREGATE.json')","(ROOT/'evidence/R37-AGGREGATE.json')",'aggregate evidence')
one("'profile':'frames-0.9.98-v108-r36-nonblocking-xhci-interrupt-recovery'","'profile':'frames-0.9.98-v108-r37-g750jm-xhci-ring-elantech-recovery'",'profile')
one('Frames 0.9.98 v108 r36 — Nonblocking xHCI Interrupt Recovery','Frames 0.9.98 v108 r37 — G750JM xHCI Ring + Elantech Recovery','cert title')
one("print('R36 PASS_VM_PENDING_PHYSICAL',iso_sha)","print('R37 PASS_VM_PENDING_PHYSICAL',iso_sha)",'PASS marker')
alln("R36-FAILURE.txt","R37-FAILURE.txt",3,'failure evidence')

oldhist="'physical_r35':'NOT_TESTED','physical_r35b':'FAIL_USB_PHYSICAL_EP0_MOUSE_TIMEOUT_TOUCHPAD_REGRESSION','physical_r35b_telemetry':'R35_F1_K1_M1_Q270_R78_E12','physical_r36':'PENDING'"
newhist="'physical_r35':'NOT_TESTED','physical_r35b':'FAIL_USB_PHYSICAL_EP0_MOUSE_TIMEOUT_TOUCHPAD_REGRESSION','physical_r35b_telemetry':'R35_F1_K1_M1_Q270_R78_E12','physical_r36':'FAIL_USB_PHYSICAL_RUNNING_EP_NO_EVENTS_TOUCHPAD_FLICKER','physical_r36_telemetry':'R36_S1_I5_D5_M8_K562_E0','physical_r37':'PENDING'"
one(oldhist,newhist,'physical history')

ns={'__name__':'__main__','__file__':str(base)}
try:
    exec(compile(src,str(base),'exec'),ns,ns)
except BaseException:
    out=Path('evidence'); out.mkdir(parents=True,exist_ok=True)
    (out/'R37-FAILURE.txt').write_text(traceback.format_exc())
    raise
